# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserofWishlist', to='loginapp.Registration'),
        ),
    ]
